In [2]:
#%%sh
# pip install -q pip --upgrade
# pip install -q --upgrade opencv-python
#pip install --user --upgrade tensorflow

In [13]:
import cv2
import boto3
import os
import numpy as np
import tensorflow as tf

In [4]:
S3 = boto3.client('s3')

In [5]:
filename = 'public/Sofy Soul.png'
image_object = S3.get_object(Bucket='pornilarity-bucket170933-production', Key=filename)
file_content = image_object["Body"].read()

In [6]:
np_array = np.fromstring(file_content, np.uint8)
np_array

/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/ipykernel/__main__.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  if __name__ == '__main__':


array([137,  80,  78, ...,  66,  96, 130], dtype=uint8)

In [9]:
image_tensor = cv2.imdecode(np_array, cv2.IMREAD_COLOR)

gray = cv2.cvtColor(image_tensor, cv2.COLOR_BGR2GRAY)

In [14]:
image = cv2.resize(gray, (100, 100))
image = np.array(image).reshape(-1, 100, 100, 1) # reshapes the image into accepted dimensions (4D tensor)
image = tf.cast(image, tf.float32)  # change data type of image to float32
image = image / 255.0

In [15]:
image

<tf.Tensor: id=3, shape=(1, 100, 100, 1), dtype=float32, numpy=
array([[[[1.        ],
         [1.        ],
         [1.        ],
         ...,
         [0.93333334],
         [0.93333334],
         [0.9372549 ]],

        [[1.        ],
         [1.        ],
         [1.        ],
         ...,
         [0.9529412 ],
         [0.95686275],
         [0.95686275]],

        [[1.        ],
         [1.        ],
         [1.        ],
         ...,
         [0.96862745],
         [0.96862745],
         [0.96862745]],

        ...,

        [[0.87058824],
         [0.6156863 ],
         [0.56078434],
         ...,
         [0.8235294 ],
         [0.7607843 ],
         [0.69411767]],

        [[0.827451  ],
         [0.5921569 ],
         [0.5568628 ],
         ...,
         [0.61960787],
         [0.62352943],
         [0.6313726 ]],

        [[0.8039216 ],
         [0.5882353 ],
         [0.5529412 ],
         ...,
         [0.7411765 ],
         [0.7137255 ],
         [0.67058825]]]

In [21]:
image = cv2.resize(gray, (100, 100))
image = np.array(image).reshape(-1, 100, 100, 1) # reshapes the image into accepted dimensions (4D tensor)
image = image.astype('float32') # change data type of image to float32
image = image / 255.0
image

array([[[[1.        ],
         [1.        ],
         [1.        ],
         ...,
         [0.93333334],
         [0.93333334],
         [0.9372549 ]],

        [[1.        ],
         [1.        ],
         [1.        ],
         ...,
         [0.9529412 ],
         [0.95686275],
         [0.95686275]],

        [[1.        ],
         [1.        ],
         [1.        ],
         ...,
         [0.96862745],
         [0.96862745],
         [0.96862745]],

        ...,

        [[0.87058824],
         [0.6156863 ],
         [0.56078434],
         ...,
         [0.8235294 ],
         [0.7607843 ],
         [0.69411767]],

        [[0.827451  ],
         [0.5921569 ],
         [0.5568628 ],
         ...,
         [0.61960787],
         [0.62352943],
         [0.6313726 ]],

        [[0.8039216 ],
         [0.5882353 ],
         [0.5529412 ],
         ...,
         [0.7411765 ],
         [0.7137255 ],
         [0.67058825]]]], dtype=float32)